### ISSUE TITLE
[Vssue]如何生成指定长度的不重复的随机数组？

### ISSUE THREAD

**Issue by lanzhi-lee** [lanzhi-lee/blog#1]
https://www.leezx.cn/posts/2020/01/01/%E5%A6%82%E4%BD%95%E7%94%9F%E6%88%90%E6%8C%87%E5%AE%9A%E9%95%BF%E5%BA%A6%E7%9A%84%E4%B8%8D%E9%87%8D%E5%A4%8D%E7%9A%84%E9%9A%8F%E6%9C%BA%E6%95%B0%E7%BB%84.html

**Comment by baibai-lee** [comment]
这是一条来自博主的测试评论
